// addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.9.9")
// addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.9.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                 % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                 % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"                 % "0.10.4")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"                  % "0.6.4")
addSbtPlugin("org.typelevel"             % "sbt-typelevel-mergify"        % "0.4.21")
addSbtPlugin("org.typelevel"             % "sbt-typelevel-github-actions" % "0.4.21")
